{
    "TK_World_Main_Deform":"TK_world",

    "TK_Spine_Start_Deform":"TK_pelvis",
    "TK_Spine_Twist_1_Deform":"TK_spine_1",
    "TK_Spine_Twist_2_Deform":"TK_spine_2",
    "TK_Spine_Twist_3_Deform":"TK_spine_3",
    "TK_Spine_Twist_4_Deform":"TK_spine_4",
    "TK_Spine_Twist_5_Deform":"TK_spine_5",
    "TK_Spine_End_Deform":"TK_chest",

    "TK_Spine_Breath_Deform":"TK_spineBreath",
    "TK_Jaw_0_Deform":"TK_jaw",

    "TK_Neck_Start_Deform":"TK_neck_1",
    "TK_Neck_Twist_2_Deform":"TK_neck_2",
    "TK_Neck_Twist_3_Deform":"TK_neck_3",
    "TK_Neck_Twist_4_Deform":"TK_neck_4",
    "TK_Neck_Head_Deform":"TK_head",

    "TK_Neck_Bk_AngleDeformer_Main_Deform": "TK_neckBk_aD",
    "TK_Neck_Jaw_AngleDeformer_Main_Deform": "TK_neckJaw_aD",

    "TK_Left_Eye_Main_Deform":"TK_eye_l",
    "TK_Left_Eye_Extra_Main_Deform":"TK_eyeExtra_l",

    "TK_Left_Shoulder_0_Deform":"TK_clav_l",
    "TK_Left_Arm_Twist_Up_1_Deform":"TK_shoulder_l",
    "TK_Left_Arm_Twist_Up_2_Deform":"TK_upperArm_1_l",
    "TK_Left_Arm_Twist_Up_3_Deform":"TK_upperArm_2_l",
    "TK_Left_Arm_Twist_Up_4_Deform":"TK_upperArm_3_l",
    "TK_Left_Arm_Twist_Up_5_Deform":"TK_upperArm_4_l",

    "TK_Left_Arm_Twist_Dwn_1_Deform":"TK_elbow_l",
    "TK_Left_Arm_Twist_Dwn_2_Deform":"TK_lowerArm_1_l",
    "TK_Left_Arm_Twist_Dwn_3_Deform":"TK_lowerArm_2_l",
    "TK_Left_Arm_Twist_Dwn_4_Deform":"TK_lowerArm_3_l",
    "TK_Left_Arm_Twist_Dwn_5_Deform":"TK_lowerArm_4_l",

    "TK_Left_Arm_Eff_Deform":"TK_wrist_l",

    "TK_Left_HandRig_Thumb_02_Deform":"TK_thumb_1_l",
    "TK_Left_HandRig_Thumb_03_Deform":"TK_thumb_2_l",
    "TK_Left_HandRig_Thumb_04_Deform":"TK_thumb_3_l",

    "TK_Left_HandRig_Index_01_Deform":"TK_index_1_l ",
    "TK_Left_HandRig_Index_02_Deform":"TK_index_2_l",
    "TK_Left_HandRig_Index_03_Deform":"TK_index_3_l",
    "TK_Left_HandRig_Index_04_Deform":"TK_index_4_l",

    "TK_Left_HandRig_Middle_01_Deform":"TK_middle_1_l",
    "TK_Left_HandRig_Middle_02_Deform":"TK_middle_2_l",
    "TK_Left_HandRig_Middle_03_Deform":"TK_middle_3_l",
    "TK_Left_HandRig_Middle_04_Deform":"TK_middle_4_l",

    "TK_Left_HandRig_Ring_01_Deform":"TK_ring_1_l",
    "TK_Left_HandRig_Ring_02_Deform":"TK_ring_2_l",
    "TK_Left_HandRig_Ring_03_Deform":"TK_ring_3_l",
    "TK_Left_HandRig_Ring_04_Deform":"TK_ring_4_l",

    "TK_Left_HandRig_Pinky_01_Deform":"TK_pinky_1_l",
    "TK_Left_HandRig_Pinky_02_Deform":"TK_pinky_2_l",
    "TK_Left_HandRig_Pinky_03_Deform":"TK_pinky_3_l",
    "TK_Left_HandRig_Pinky_04_Deform":"TK_pinky_4_l",

    "TK_Left_Leg_Twist_Up_1_Deform":"TK_thigh_l",
    "TK_Left_Leg_Twist_Up_2_Deform":"TK_upperLeg_1_l",
    "TK_Left_Leg_Twist_Up_3_Deform":"TK_upperLeg_2_l",
    "TK_Left_Leg_Twist_Up_4_Deform":"TK_upperLeg_3_l",
    "TK_Left_Leg_Twist_Up_5_Deform":"TK_upperLeg_4_l",

    "TK_Left_Leg_Twist_Dwn_1_Deform":"TK_calf_l",
    "TK_Left_Leg_Twist_Dwn_2_Deform":"TK_lowerLeg_1_l",
    "TK_Left_Leg_Twist_Dwn_3_Deform":"TK_lowerLeg_2_l",
    "TK_Left_Leg_Twist_Dwn_4_Deform":"TK_lowerLeg_3_l",
    "TK_Left_Leg_Twist_Dwn_5_Deform":"TK_lowerLeg_4_l",

    "TK_Left_Leg_Eff_Deform":"TK_foot_l",
    "TK_Left_Foot_Tip_Deform":"TK_toeBase_l",


    "TK_Left_Hips_Belly_AngleDeformer_Main_Deform": "TK_belly_aD_l",
    "TK_Left_Hips_Gluteus_AngleDeformer_Main_Deform": "TK_gluteus_aD_l",
    "TK_Left_Hip_SideExtra_Main_Deform":"TK_hipsSide_aD_l",
    "TK_Left_Hips_Ft_Stretch_Deform":"TK_hipsFt_st_l",
    "TK_Left_Hips_Bk_Stretch_Deform":"TK_hipsBk_st_l",

    "TK_Left_Mastoid_1_Deform":"TK_mastoid_1_l",
    "TK_Left_Mastoid_2_Deform":"TK_mastoid_2_l",
    "TK_Left_Mastoid_3_Deform":"TK_mastoid_3_l",
    "TK_Left_Mastoid_4_Deform":"TK_mastoid_4_l",
    "TK_Left_Mastoid_5_Deform":"TK_mastoid_5_l",

    "TK_Left_Ham_AngleDeformer_Main_Deform": "TK_ham_aD_l",
    "TK_Left_Knee_Up_AngleDeformer_Main_Deform": "TK_kneeUp_aD_l",
    "TK_Left_Knee_Dwn_AngleDeformer_Main_Deform": "TK_kneeDwn_aD_l",
    "TK_Left_Knee_Stretch_Deform":"TK_knee_st_l",

    "TK_Left_Ankle_Ext_AngleDeformer_Main_Deform": "TK_ankleExt_aD_l",
    "TK_Left_Ankle_Int_AngleDeformer_Main_Deform": "TK_ankleInt_aD_l",
    "TK_Left_Toes_Int_AngleDeformer_Main_Deform": "TK_toesInt_aD_l",

    "TK_Left_Shoulder_Up_Deltoid_Stretch_Deform":"TK_deltoidUp_st_l",
    "TK_Left_Shoulder_Pectoral_Stretch_Deform":"TK_pectoral_st_l",
    "TK_Left_Shoulder_Latissimus_Stretch_Deform":"TK_latissimus_st_l",
    "TK_Left_Shoulder_Ft_Deltoid_Stretch_Deform":"TK_deltoidFt_st_l",
    "TK_Left_Shoulder_Bk_Deltoid_Stretch_Deform":"TK_deltoidBk_st_l",
    "TK_Left_Shoulder_ArmpitY_AngleDeformer_Main_Deform": "TK_armpitY_aD_l",
    "TK_Left_Clavicle_Trapezius_Stretch_Deform":"TK_trapezius_st_l",

    "TK_Left_Biceps_AngleDeformer_Main_Deform": "TK_biceps_aD_l",

    "TK_Left_Elbow_Up_AngleDeformer_Main_Deform": "TK_elbowUp_aD_l",
    "TK_Left_Elbow_Dwn_AngleDeformer_Main_Deform": "TK_elbowDwn_aD_l",
    "TK_Left_Elbow_Stretch_Deform":"TK_elbow_st_l",

    "TK_Left_Wrist_Ext_AngleDeformer_Main_Deform": "TK_wristExt_aD_l",
    "TK_Left_Wrist_Up_AngleDeformer_Main_Deform": "TK_wristUp_aD_l",
    "TK_Left_Wrist_Dwn_AngleDeformer_Main_Deform": "TK_wristDwn_aD_l",
    "TK_Left_Wrist_Int_AngleDeformer_Main_Deform": "TK_wristInt_aD_l",

    "TK_Left_Top_Thumb1AngleDeformer_Main_Deform": "TK_thumb1_aD_l",
    "TK_Left_Top_Thumb3AngleDeformer1_Main_Deform": "TK_thumb3_1_aD_l",
    "TK_Left_Top_Thumb3AngleDeformer2_Main_Deform": "TK_thumb3_2_l",
    "TK_Left_ThumbBase_Stretch_Deform":"TK_thumbBase_st_l",
    "TK_Left_ThumbWeb_Stretch_Deform":"TK_thumbWeb_st_l",
    "TK_Left_Thumb2_Stretch_Deform":"TK_thumb2_st_l",
    "TK_Left_Thumb3_Stretch_Deform":"TK_thumb3_st_l",

    "TK_Left_Top_Index1AngleDeformer_Main_Deform": "TK_index1_aD_l",
    "TK_Left_Top_Index2AngleDeformer1_Main_Deform": "TK_index2_1_aD_l",
    "TK_Left_Top_Index2AngleDeformer2_Main_Deform": "TK_index2_2_aD_l",
    "TK_Left_Top_Index3AngleDeformer1_Main_Deform": "TK_index3_1_aD_l",
    "TK_Left_Top_Index3AngleDeformer2_Main_Deform": "TK_index3_2_aD_l",
    "TK_Left_Index_Stretch1_Deform":"TK_index_st_1_l",
    "TK_Left_Index_Stretch2_Deform":"TK_index_st_2_l",
    "TK_Left_Index_Stretch3_Deform":"TK_index_st_3_l",

    "TK_Left_Top_Middle1AngleDeformer_Main_Deform": "TK_middle1_aD_l",
    "TK_Left_Top_Middle2AngleDeformer1_Main_Deform": "TK_middle2_1_aD_l",
    "TK_Left_Top_Middle2AngleDeformer2_Main_Deform": "TK_middle2_2_aD_l",
    "TK_Left_Top_Middle3AngleDeformer1_Main_Deform": "TK_middle3_1_aD_l",
    "TK_Left_Top_Middle3AngleDeformer2_Main_Deform": "TK_middle3_2_aD_l",
    "TK_Left_Middle_Stretch1_Deform":"TK_middle_st_1_l",
    "TK_Left_Middle_Stretch2_Deform":"TK_middle_st_2_l",
    "TK_Left_Middle_Stretch3_Deform":"TK_middle_st_3_l",

    "TK_Left_Top_Ring1AngleDeformer_Main_Deform": "TK_ring1_aD_l",
    "TK_Left_Top_Ring2AngleDeformer1_Main_Deform": "TK_ring2_1_aD_l",
    "TK_Left_Top_Ring2AngleDeformer2_Main_Deform": "TK_ring2_2_aD_l",
    "TK_Left_Top_Ring3AngleDeformer1_Main_Deform": "TK_ring3_1_aD_l",
    "TK_Left_Top_Ring3AngleDeformer2_Main_Deform": "TK_ring3_2_aD_l",
    "TK_Left_Ring_Stretch1_Deform":"TK_ring_st_1_l",
    "TK_Left_Ring_Stretch2_Deform":"TK_ring_st_2_l",
    "TK_Left_Ring_Stretch3_Deform":"TK_ring_st_3_l",

    "TK_Left_Top_Pinky1AngleDeformer_Main_Deform": "TK_pinky1_aD_l",
    "TK_Left_Top_Pinky2AngleDeformer1_Main_Deform": "TK_pinky2_1_aD_l",
    "TK_Left_Top_Pinky2AngleDeformer2_Main_Deform": "TK_pinky2_2_aD_l",
    "TK_Left_Top_Pinky3AngleDeformer1_Main_Deform": "TK_pinky3_1_aD_l",
    "TK_Left_Top_Pinky3AngleDeformer2_Main_Deform": "TK_pinky3_2_aD_l",
    "TK_Left_Pinky_Stretch1_Deform":"TK_pinky_st_1_l",
    "TK_Left_Pinky_Stretch2_Deform":"TK_pinky_st_2_l",
    "TK_Left_Pinky_Stretch3_Deform":"TK_pinky_st_3_l",



    "TK_Right_Eye_Main_Deform":"TK_eye_r",
    "TK_Right_Eye_Extra_Main_Deform":"TK_eyeExtra_r",

    "TK_Right_Shoulder_0_Deform":"TK_clav_r",
    "TK_Right_Arm_Twist_Up_1_Deform":"TK_shoulder_r",
    "TK_Right_Arm_Twist_Up_2_Deform":"TK_upperArm_1_r",
    "TK_Right_Arm_Twist_Up_3_Deform":"TK_upperArm_2_r",
    "TK_Right_Arm_Twist_Up_4_Deform":"TK_upperArm_3_r",
    "TK_Right_Arm_Twist_Up_5_Deform":"TK_upperArm_4_r",

    "TK_Right_Arm_Twist_Dwn_1_Deform":"TK_elbow_r",
    "TK_Right_Arm_Twist_Dwn_2_Deform":"TK_lowerArm_1_r",
    "TK_Right_Arm_Twist_Dwn_3_Deform":"TK_lowerArm_2_r",
    "TK_Right_Arm_Twist_Dwn_4_Deform":"TK_lowerArm_3_r",
    "TK_Right_Arm_Twist_Dwn_5_Deform":"TK_lowerArm_4_r",

    "TK_Right_Arm_Eff_Deform":"TK_wrist_r",

    "TK_Right_HandRig_Thumb_02_Deform":"TK_thumb_1_r",
    "TK_Right_HandRig_Thumb_03_Deform":"TK_thumb_2_r",
    "TK_Right_HandRig_Thumb_04_Deform":"TK_thumb_3_r",

    "TK_Right_HandRig_Index_01_Deform":"TK_index_1_l ",
    "TK_Right_HandRig_Index_02_Deform":"TK_index_2_r",
    "TK_Right_HandRig_Index_03_Deform":"TK_index_3_r",
    "TK_Right_HandRig_Index_04_Deform":"TK_index_4_r",

    "TK_Right_HandRig_Middle_01_Deform":"TK_middle_1_r",
    "TK_Right_HandRig_Middle_02_Deform":"TK_middle_2_r",
    "TK_Right_HandRig_Middle_03_Deform":"TK_middle_3_r",
    "TK_Right_HandRig_Middle_04_Deform":"TK_middle_4_r",

    "TK_Right_HandRig_Ring_01_Deform":"TK_ring_1_r",
    "TK_Right_HandRig_Ring_02_Deform":"TK_ring_2_r",
    "TK_Right_HandRig_Ring_03_Deform":"TK_ring_3_r",
    "TK_Right_HandRig_Ring_04_Deform":"TK_ring_4_r",

    "TK_Right_HandRig_Pinky_01_Deform":"TK_pinky_1_r",
    "TK_Right_HandRig_Pinky_02_Deform":"TK_pinky_2_r",
    "TK_Right_HandRig_Pinky_03_Deform":"TK_pinky_3_r",
    "TK_Right_HandRig_Pinky_04_Deform":"TK_pinky_4_r",

    "TK_Right_Leg_Twist_Up_1_Deform":"TK_thigh_r",
    "TK_Right_Leg_Twist_Up_2_Deform":"TK_upperLeg_1_r",
    "TK_Right_Leg_Twist_Up_3_Deform":"TK_upperLeg_2_r",
    "TK_Right_Leg_Twist_Up_4_Deform":"TK_upperLeg_3_r",
    "TK_Right_Leg_Twist_Up_5_Deform":"TK_upperLeg_4_r",

    "TK_Right_Leg_Twist_Dwn_1_Deform":"TK_calf_r",
    "TK_Right_Leg_Twist_Dwn_2_Deform":"TK_lowerLeg_1_r",
    "TK_Right_Leg_Twist_Dwn_3_Deform":"TK_lowerLeg_2_r",
    "TK_Right_Leg_Twist_Dwn_4_Deform":"TK_lowerLeg_3_r",
    "TK_Right_Leg_Twist_Dwn_5_Deform":"TK_lowerLeg_4_r",

    "TK_Right_Leg_Eff_Deform":"TK_foot_r",
    "TK_Right_Foot_Tip_Deform":"TK_toeBase_r",


    "TK_Right_Hips_Belly_AngleDeformer_Main_Deform": "TK_belly_aD_r",
    "TK_Right_Hips_Gluteus_AngleDeformer_Main_Deform": "TK_gluteus_aD_r",
    "TK_Right_Hip_SideExtra_Main_Deform":"TK_hipsSide_aD_r",
    "TK_Right_Hips_Ft_Stretch_Deform":"TK_hipsFt_st_r",
    "TK_Right_Hips_Bk_Stretch_Deform":"TK_hipsBk_st_r",

    "TK_Right_Mastoid_1_Deform":"TK_mastoid_1_r",
    "TK_Right_Mastoid_2_Deform":"TK_mastoid_2_r",
    "TK_Right_Mastoid_3_Deform":"TK_mastoid_3_r",
    "TK_Right_Mastoid_4_Deform":"TK_mastoid_4_r",
    "TK_Right_Mastoid_5_Deform":"TK_mastoid_5_r",

    "TK_Right_Ham_AngleDeformer_Main_Deform": "TK_ham_aD_r",
    "TK_Right_Knee_Up_AngleDeformer_Main_Deform": "TK_kneeUp_aD_r",
    "TK_Right_Knee_Dwn_AngleDeformer_Main_Deform": "TK_kneeDwn_aD_r",
    "TK_Right_Knee_Stretch_Deform":"TK_knee_st_r",

    "TK_Right_Ankle_Ext_AngleDeformer_Main_Deform": "TK_ankleExt_aD_r",
    "TK_Right_Ankle_Int_AngleDeformer_Main_Deform": "TK_ankleInt_aD_r",
    "TK_Right_Toes_Int_AngleDeformer_Main_Deform": "TK_toesInt_aD_r",

    "TK_Right_Shoulder_Up_Deltoid_Stretch_Deform":"TK_deltoidUp_st_r",
    "TK_Right_Shoulder_Pectoral_Stretch_Deform":"TK_pectoral_st_r",
    "TK_Right_Shoulder_Latissimus_Stretch_Deform":"TK_latissimus_st_r",
    "TK_Right_Shoulder_Ft_Deltoid_Stretch_Deform":"TK_deltoidFt_st_r",
    "TK_Right_Shoulder_Bk_Deltoid_Stretch_Deform":"TK_deltoidBk_st_r",
    "TK_Right_Shoulder_ArmpitY_AngleDeformer_Main_Deform": "TK_armpitY_aD_r",
    "TK_Right_Clavicle_Trapezius_Stretch_Deform":"TK_trapezius_st_r",

    "TK_Right_Biceps_AngleDeformer_Main_Deform": "TK_biceps_aD_r",

    "TK_Right_Elbow_Up_AngleDeformer_Main_Deform": "TK_elbowUp_aD_r",
    "TK_Right_Elbow_Dwn_AngleDeformer_Main_Deform": "TK_elbowDwn_aD_r",
    "TK_Right_Elbow_Stretch_Deform":"TK_elbow_st_r",

    "TK_Right_Wrist_Ext_AngleDeformer_Main_Deform": "TK_wristExt_aD_r",
    "TK_Right_Wrist_Up_AngleDeformer_Main_Deform": "TK_wristUp_aD_r",
    "TK_Right_Wrist_Dwn_AngleDeformer_Main_Deform": "TK_wristDwn_aD_r",
    "TK_Right_Wrist_Int_AngleDeformer_Main_Deform": "TK_wristInt_aD_r",

    "TK_Right_Top_Thumb1AngleDeformer_Main_Deform": "TK_thumb1_aD_r",
    "TK_Right_Top_Thumb3AngleDeformer1_Main_Deform": "TK_thumb3_1_aD_r",
    "TK_Right_Top_Thumb3AngleDeformer2_Main_Deform": "TK_thumb3_2_r",
    "TK_Right_ThumbBase_Stretch_Deform":"TK_thumbBase_st_r",
    "TK_Right_ThumbWeb_Stretch_Deform":"TK_thumbWeb_st_r",
    "TK_Right_Thumb2_Stretch_Deform":"TK_thumb2_st_r",
    "TK_Right_Thumb3_Stretch_Deform":"TK_thumb3_st_r",

    "TK_Right_Top_Index1AngleDeformer_Main_Deform": "TK_index1_aD_r",
    "TK_Right_Top_Index2AngleDeformer1_Main_Deform": "TK_index2_1_aD_r",
    "TK_Right_Top_Index2AngleDeformer2_Main_Deform": "TK_index2_2_aD_r",
    "TK_Right_Top_Index3AngleDeformer1_Main_Deform": "TK_index3_1_aD_r",
    "TK_Right_Top_Index3AngleDeformer2_Main_Deform": "TK_index3_2_aD_r",
    "TK_Right_Index_Stretch1_Deform":"TK_index_st_1_r",
    "TK_Right_Index_Stretch2_Deform":"TK_index_st_2_r",
    "TK_Right_Index_Stretch3_Deform":"TK_index_st_3_r",

    "TK_Right_Top_Middle1AngleDeformer_Main_Deform": "TK_middle1_aD_r",
    "TK_Right_Top_Middle2AngleDeformer1_Main_Deform": "TK_middle2_1_aD_r",
    "TK_Right_Top_Middle2AngleDeformer2_Main_Deform": "TK_middle2_2_aD_r",
    "TK_Right_Top_Middle3AngleDeformer1_Main_Deform": "TK_middle3_1_aD_r",
    "TK_Right_Top_Middle3AngleDeformer2_Main_Deform": "TK_middle3_2_aD_r",
    "TK_Right_Middle_Stretch1_Deform":"TK_middle_st_1_r",
    "TK_Right_Middle_Stretch2_Deform":"TK_middle_st_2_r",
    "TK_Right_Middle_Stretch3_Deform":"TK_middle_st_3_r",

    "TK_Right_Top_Ring1AngleDeformer_Main_Deform": "TK_ring1_aD_r",
    "TK_Right_Top_Ring2AngleDeformer1_Main_Deform": "TK_ring2_1_aD_r",
    "TK_Right_Top_Ring2AngleDeformer2_Main_Deform": "TK_ring2_2_aD_r",
    "TK_Right_Top_Ring3AngleDeformer1_Main_Deform": "TK_ring3_1_aD_r",
    "TK_Right_Top_Ring3AngleDeformer2_Main_Deform": "TK_ring3_2_aD_r",
    "TK_Right_Ring_Stretch1_Deform":"TK_ring_st_1_r",
    "TK_Right_Ring_Stretch2_Deform":"TK_ring_st_2_r",
    "TK_Right_Ring_Stretch3_Deform":"TK_ring_st_3_r",

    "TK_Right_Top_Pinky1AngleDeformer_Main_Deform": "TK_pinky1_aD_r",
    "TK_Right_Top_Pinky2AngleDeformer1_Main_Deform": "TK_pinky2_1_aD_r",
    "TK_Right_Top_Pinky2AngleDeformer2_Main_Deform": "TK_pinky2_2_aD_r",
    "TK_Right_Top_Pinky3AngleDeformer1_Main_Deform": "TK_pinky3_1_aD_r",
    "TK_Right_Top_Pinky3AngleDeformer2_Main_Deform": "TK_pinky3_2_aD_r",
    "TK_Right_Pinky_Stretch1_Deform":"TK_pinky_st_1_r",
    "TK_Right_Pinky_Stretch2_Deform":"TK_pinky_st_2_r",
    "TK_Right_Pinky_Stretch3_Deform":"TK_pinky_st_3_r",
}