[
    {'name': 'Body_Main_Deform',  'type': 'Deform',  'parent': None},
    {'name': 'Body_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Body_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_1_Main_Deform'},
    {'name': 'Body_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_2_Main_Deform'},
    {'name': 'Body_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_3_Main_Deform'},
    {'name': 'Body_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_4_Main_Deform'},
    {'name': 'Body_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_5_Main_Deform'},
    {'name': 'Body_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_6_Main_Deform'},
    {'name': 'Body_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_7_Main_Deform'},
    {'name': 'Body_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_8_Main_Deform'},
    {'name': 'Body_Rib_10_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_9_Main_Deform'},
    {'name': 'Body_Rib_11_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_10_Main_Deform'},
    {'name': 'Body_Rib_12_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_11_Main_Deform'},
    {'name': 'Body_Rib_13_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_12_Main_Deform'},
    {'name': 'Body_Rib_14_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_13_Main_Deform'},
    {'name': 'Body_Rib_15_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_14_Main_Deform'},
    {'name': 'Body_Rib_16_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_15_Main_Deform'},
    {'name': 'Body_Rib_17_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_16_Main_Deform'},
    {'name': 'Body_Rib_18_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_17_Main_Deform'},
    {'name': 'Body_Rib_19_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_18_Main_Deform'},
    {'name': 'Body_Rib_20_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_19_Main_Deform'},
    {'name': 'Body_Rib_21_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_20_Main_Deform'},
    {'name': 'Body_Rib_22_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_21_Main_Deform'},
    {'name': 'Body_Rib_23_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_22_Main_Deform'},
    {'name': 'Body_Rib_24_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_23_Main_Deform'},
    {'name': 'Body_Rib_25_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_24_Main_Deform'},
    {'name': 'Body_Rib_26_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_25_Main_Deform'},
    {'name': 'Body_Rib_27_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_26_Main_Deform'},
    {'name': 'Body_Rib_28_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_27_Main_Deform'},

    {'name': 'Spine_rib_04_Main_Deform',  'type': 'Deform',  'parent': 'Spine_rib_03_Main_Deform'},
    {'name': 'Spine_rib_03_Main_Deform',  'type': 'Deform',  'parent': 'Spine_rib_02_Main_Deform'},
    {'name': 'Spine_rib_02_Main_Deform',  'type': 'Deform',  'parent': 'Spine_rib_01_Main_Deform'},
    {'name': 'Spine_rib_01_Main_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},

    {'name': 'Tail_rib_01_Main_Deform',  'type': 'Deform',  'parent': 'Spine_rib_04_Main_Deform'},
    {'name': 'Tail_rib_02_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_01_Main_Deform'},
    {'name': 'Tail_rib_03_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_02_Main_Deform'},
    {'name': 'Tail_rib_04_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_03_Main_Deform'},
    {'name': 'Tail_rib_05_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_04_Main_Deform'},
    {'name': 'Tail_rib_06_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_05_Main_Deform'},
    {'name': 'Tail_rib_07_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_06_Main_Deform'},
    {'name': 'Tail_rib_08_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_07_Main_Deform'},
    {'name': 'Tail_rib_09_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_08_Main_Deform'},
    {'name': 'Tail_rib_10_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_09_Main_Deform'},
    {'name': 'Tail_rib_11_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_10_Main_Deform'},
    {'name': 'Tail_rib_12_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_11_Main_Deform'},
    {'name': 'Tail_rib_13_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_12_Main_Deform'},
    {'name': 'Tail_rib_14_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_13_Main_Deform'},
    {'name': 'Tail_rib_15_Main_Deform',  'type': 'Deform',  'parent': 'Tail_rib_14_Main_Deform'},

    {'name': 'Left_Arm_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_21_Main_Deform'},
    {'name': 'Left_Arm_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_1_Main_Deform'},
    {'name': 'Left_Arm_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_2_Main_Deform'},
    {'name': 'Left_Arm_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_3_Main_Deform'},
    {'name': 'Left_Arm_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_4_Main_Deform'},
    {'name': 'Left_Arm_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_5_Main_Deform'},
    {'name': 'Left_Arm_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_6_Main_Deform'},
    {'name': 'Left_Arm_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_7_Main_Deform'},
    {'name': 'Left_Arm_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_8_Main_Deform'},
    {'name': 'Left_Arm_Rib_10_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_9_Main_Deform'},
    {'name': 'Left_Arm_Rib_11_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_10_Main_Deform'},
    {'name': 'Left_Arm_Rib_12_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_11_Main_Deform'},
    {'name': 'Left_Arm_Rib_13_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Rib_12_Main_Deform'},

    {'name': 'Left_Leg_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Left_Leg_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_1_Main_Deform'},
    {'name': 'Left_Leg_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_2_Main_Deform'},
    {'name': 'Left_Leg_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_3_Main_Deform'},
    {'name': 'Left_Leg_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_4_Main_Deform'},
    {'name': 'Left_Leg_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_5_Main_Deform'},
    {'name': 'Left_Leg_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_6_Main_Deform'},
    {'name': 'Left_Leg_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_7_Main_Deform'},
    {'name': 'Left_Leg_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Rib_8_Main_Deform'},

    {'name': 'Right_Arm_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Rib_21_Main_Deform'},
    {'name': 'Right_Arm_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_1_Main_Deform'},
    {'name': 'Right_Arm_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_2_Main_Deform'},
    {'name': 'Right_Arm_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_3_Main_Deform'},
    {'name': 'Right_Arm_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_4_Main_Deform'},
    {'name': 'Right_Arm_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_5_Main_Deform'},
    {'name': 'Right_Arm_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_6_Main_Deform'},
    {'name': 'Right_Arm_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_7_Main_Deform'},
    {'name': 'Right_Arm_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_8_Main_Deform'},
    {'name': 'Right_Arm_Rib_10_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_9_Main_Deform'},
    {'name': 'Right_Arm_Rib_11_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_10_Main_Deform'},
    {'name': 'Right_Arm_Rib_12_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_11_Main_Deform'},
    {'name': 'Right_Arm_Rib_13_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Rib_12_Main_Deform'},

    {'name': 'Right_Leg_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Right_Leg_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_1_Main_Deform'},
    {'name': 'Right_Leg_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_2_Main_Deform'},
    {'name': 'Right_Leg_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_3_Main_Deform'},
    {'name': 'Right_Leg_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_4_Main_Deform'},
    {'name': 'Right_Leg_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_5_Main_Deform'},
    {'name': 'Right_Leg_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_6_Main_Deform'},
    {'name': 'Right_Leg_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_7_Main_Deform'},
    {'name': 'Right_Leg_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Rib_8_Main_Deform'},

    {'name': 'Hair_01_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_02_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_03_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_04_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_05_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_06_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_07_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_08_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_09_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_10_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_11_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_12_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},
    {'name': 'Hair_13_01_0_Deform',  'type': 'Deform',  'parent': 'Body_Rib_28_Main_Deform'},

    {'name': 'Spine_Start_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Spine_Twist_1_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Spine_Twist_2_Deform',  'type': 'Deform',  'parent': 'Spine_Twist_1_Deform'},
    {'name': 'Spine_Part2_Deform',  'type': 'Deform',  'parent': 'Spine_Twist_2_Deform'},
    {'name': 'Spine_Twist_3_Deform',  'type': 'Deform',  'parent': 'Spine_Part2_Deform'},
    {'name': 'Spine_Twist_4_Deform',  'type': 'Deform',  'parent': 'Spine_Twist_3_Deform'},
    {'name': 'Spine_Twist_5_Deform',  'type': 'Deform',  'parent': 'Spine_Twist_4_Deform'},
    {'name': 'Spine_End_Deform',  'type': 'Deform',  'parent': 'Spine_Twist_5_Deform'},

    {'name': 'Spine_Breath_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},

    {'name': 'Tail_1_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},

    {'name': 'Neck_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Neck_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_1_Main_Deform'},
    {'name': 'Neck_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_2_Main_Deform'},
    {'name': 'Neck_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_3_Main_Deform'},
    {'name': 'Neck_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_4_Main_Deform'},
    {'name': 'Neck_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_5_Main_Deform'},
    {'name': 'Neck_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_6_Main_Deform'},
    {'name': 'Neck_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_7_Main_Deform'},
    {'name': 'Neck_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Neck_Rib_8_Main_Deform'},

    {'name': 'Tail_Rib_1_Main_Deform',  'type': 'Deform',  'parent': 'Body_Main_Deform'},
    {'name': 'Tail_Rib_2_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_1_Main_Deform'},
    {'name': 'Tail_Rib_3_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_2_Main_Deform'},
    {'name': 'Tail_Rib_4_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_3_Main_Deform'},
    {'name': 'Tail_Rib_5_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_4_Main_Deform'},
    {'name': 'Tail_Rib_6_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_5_Main_Deform'},
    {'name': 'Tail_Rib_7_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_6_Main_Deform'},
    {'name': 'Tail_Rib_8_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_7_Main_Deform'},
    {'name': 'Tail_Rib_9_Main_Deform',  'type': 'Deform',  'parent': 'Tail_Rib_8_Main_Deform'},

    {'name': 'Tongue_rib_02_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_01_Main_Deform'},
    {'name': 'Tongue_rib_03_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_02_Main_Deform'},
    {'name': 'Tongue_rib_04_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_03_Main_Deform'},
    {'name': 'Tongue_rib_05_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_04_Main_Deform'},
    {'name': 'Tongue_rib_06_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_05_Main_Deform'},
    {'name': 'Tongue_rib_07_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_06_Main_Deform'},
    {'name': 'Tongue_rib_08_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_07_Main_Deform'},
    {'name': 'Tongue_rib_09_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_08_Main_Deform'},
    {'name': 'Tongue_rib_10_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_09_Main_Deform'},
    {'name': 'Tongue_rib_11_Main_Deform',  'type': 'Deform',  'parent': 'Tongue_rib_10_Main_Deform'},

    {'name': 'Neck_Start_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},
    {'name': 'Neck_Twist_1_Deform',  'type': 'Deform',  'parent': 'Neck_Start_Deform'},
    {'name': 'Neck_Twist_2_Deform',  'type': 'Deform',  'parent': 'Neck_Twist_1_Deform'},
    {'name': 'Neck_Part2_Deform',  'type': 'Deform',  'parent': 'Neck_Twist_2_Deform'},
    {'name': 'Neck_Twist_3_Deform',  'type': 'Deform',  'parent': 'Neck_Part2_Deform'},
    {'name': 'Neck_Twist_4_Deform',  'type': 'Deform',  'parent': 'Neck_Twist_3_Deform'},
    {'name': 'Neck_Twist_5_Deform',  'type': 'Deform',  'parent': 'Neck_Twist_4_Deform'},
    {'name': 'Neck_End_Deform',  'type': 'Deform',  'parent': 'Neck_Twist_5_Deform'},

    {'name': 'Jaw_0_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},

    {'name': 'Neck_Head_Deform',  'type': 'Deform',  'parent': 'Neck_Middle_Deform'},
    {'name': 'Neck_Middle_Deform',  'type': 'Deform',  'parent': 'Neck_Start_Deform'},

    {'name': 'Left_Eye_Main_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},
    {'name': 'Left_Eye_Extra_Main_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},

    {'name': 'Left_Shoulder_0_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},
    {'name': 'Left_Arm_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_0_Deform'},
    {'name': 'Left_Arm_Twist_Up_1_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_Start_Deform'},
    {'name': 'Left_Arm_Twist_Up_2_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_1_Deform'},
    {'name': 'Left_Arm_Twist_Up_3_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_2_Deform'},
    {'name': 'Left_Arm_Twist_Up_4_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_3_Deform'},
    {'name': 'Left_Arm_Twist_Up_5_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_4_Deform'},
    {'name': 'Left_Arm_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_5_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_End_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_1_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_2_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_1_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_3_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_2_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_4_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_3_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_5_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_4_Deform'},
    {'name': 'Left_Arm_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_5_Deform'},
    {'name': 'Left_Arm_Eff_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_End_Deform'},

    {'name': 'Left_HandRig_Hand_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Eff_Deform'},
    {'name': 'Left_Forearm_0_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandProp_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'}, # Added for Light
    {'name': 'Left_HandRig_Hand_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Thumb_02_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Thumb_02_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_02_Deform'},
    {'name': 'Left_HandRig_Thumb_03_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_02_Deform'},
    {'name': 'Left_HandRig_Thumb_03_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_03_Deform'},
    {'name': 'Left_HandRig_Thumb_04_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_03_Deform'},
    {'name': 'Left_HandRig_Index_01_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Index_01_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_01_Deform'},
    {'name': 'Left_HandRig_Index_02_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_01_Deform'},
    {'name': 'Left_HandRig_Index_02_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_02_Deform'},
    {'name': 'Left_HandRig_Index_03_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_02_Deform'},
    {'name': 'Left_HandRig_Index_03_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_03_Deform'},
    {'name': 'Left_HandRig_Index_04_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_03_Deform'},
    {'name': 'Left_HandRig_Middle_01_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Middle_01_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_01_Deform'},
    {'name': 'Left_HandRig_Middle_02_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_01_Deform'},
    {'name': 'Left_HandRig_Middle_02_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_02_Deform'},
    {'name': 'Left_HandRig_Middle_03_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_02_Deform'},
    {'name': 'Left_HandRig_Middle_03_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_03_Deform'},
    {'name': 'Left_HandRig_Middle_04_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_03_Deform'},
    {'name': 'Left_HandRig_Ring_01_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Ring_01_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_01_Deform'},
    {'name': 'Left_HandRig_Ring_02_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_01_Deform'},
    {'name': 'Left_HandRig_Ring_02_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_02_Deform'},
    {'name': 'Left_HandRig_Ring_03_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_02_Deform'},
    {'name': 'Left_HandRig_Ring_03_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_03_Deform'},
    {'name': 'Left_HandRig_Ring_04_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_03_Deform'},
    {'name': 'Left_HandRig_Pinky_01_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_HandRig_Pinky_01_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_01_Deform'},
    {'name': 'Left_HandRig_Pinky_02_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_01_Deform'},
    {'name': 'Left_HandRig_Pinky_02_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_02_Deform'},
    {'name': 'Left_HandRig_Pinky_03_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_02_Deform'},
    {'name': 'Left_HandRig_Pinky_03_Semi_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_03_Deform'},
    {'name': 'Left_HandRig_Pinky_04_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_03_Deform'},

    {'name': 'Left_Pelvis_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Leg_Root_Skin_Main_Deform',  'type': 'Deform',  'parent': 'Left_Pelvis_Main_Deform'},

    {'name': 'Left_Leg_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Root_Skin_Main_Deform'},
    {'name': 'Left_Leg_Twist_Up_1_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_Start_Deform'},
    {'name': 'Left_Leg_Twist_Up_2_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_1_Deform'},
    {'name': 'Left_Leg_Twist_Up_3_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_2_Deform'},
    {'name': 'Left_Leg_Twist_Up_4_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_3_Deform'},
    {'name': 'Left_Leg_Twist_Up_5_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_4_Deform'},
    {'name': 'Left_Leg_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_5_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_End_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_1_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_2_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_1_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_3_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_2_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_4_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_3_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_5_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_4_Deform'},
    {'name': 'Left_Leg_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_5_Deform'},
    {'name': 'Left_Leg_Eff_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_End_Deform'},
    {'name': 'Left_Foot_Tip_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Eff_Deform'},

    {'name': 'Left_RearLeg_Pelvis_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},

    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_1',  'type': 'Deform',  'parent': 'Left_RearLeg_Pelvis_Main_Deform'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_2',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_1'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_3',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_2'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_4_0',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_3'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_4',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_4_0'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_4_1',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_4'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_5',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_4_1'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_6',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_5'},
    {'name': 'Left_RearLeg_Rounding_Deformer_Deformer_7',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_6'},

    {'name': 'Left_RearLeg_Meta_FK_def_0_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_Rounding_Deformer_Deformer_7'},

    {'name': 'Left_RearLeg_FK_Ball_def_0_Deform',  'type': 'Deform',  'parent': ['Left_RearLeg_Meta_FK_def_0_Deform',"Left_RearFoot_Twist_Meta_5_Deform"] },
    {'name': 'Left_RearLeg_FK_Toe_def_0_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_FK_Ball_def_0_Deform'},

    {'name': 'Left_Toe_LittleThumb_1_Main_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_Meta_FK_def_0_Deform'},
    {'name': 'Left_Toe_Thumb_1_Main_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_Meta_FK_def_0_Deform'},
    {'name': 'Left_Toe_Pinky_1_Main_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_FK_Toe_def_0_Deform'},
    {'name': 'Left_Toe_Middle_1_Main_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_FK_Toe_def_0_Deform'},
    {'name': 'Left_Toe_Index_1_Main_Deform',  'type': 'Deform',  'parent': 'Left_RearLeg_FK_Toe_def_0_Deform'},

    {'name': 'Left_Wrist_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_Wrist_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_Wrist_Int_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},
    {'name': 'Left_Wrist_Ext_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Hand_Deform'},

    {'name': 'Left_Hips_Belly_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Hips_Ft_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Hips_Side_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Hip_SideExtra_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Hips_Gluteus_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Left_Hips_Bk_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},

    {'name': 'Left_Ham_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_End_Deform'},
    {'name': 'Left_Knee_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_End_Deform'},
    {'name': 'Left_Knee_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Knee_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_Leg_Twist_Up_End_Deform'},

    {'name': 'Left_Shoulder_Latissimus_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_0_Deform'},
    {'name': 'Left_Biceps_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_End_Deform'},
    {'name': 'Left_Elbow_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_End_Deform'},
    {'name': 'Left_Elbow_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Elbow_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_End_Deform'},

    {'name': 'Left_ThumbBase_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_02_Deform'},
    {'name': 'Left_Top_Thumb1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_03_Deform'},
    {'name': 'Left_Top_Thumb3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_04_Deform'},
    {'name': 'Left_Top_Thumb3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_04_Deform'},
    {'name': 'Left_ThumbWeb_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_03_Deform'},
    {'name': 'Left_Thumb2_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_03_Deform'},
    {'name': 'Left_Thumb3_Stretch_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Thumb_04_Deform'},
    
    {'name': 'Left_Top_Index1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_02_Deform'},
    {'name': 'Left_Top_Index2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_03_Deform'},
    {'name': 'Left_Top_Index2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_03_Deform'},
    {'name': 'Left_Top_Index3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_04_Deform'},
    {'name': 'Left_Top_Index3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_04_Deform'},
    {'name': 'Left_Index_Stretch1_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_02_Deform'},
    {'name': 'Left_Index_Stretch2_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_03_Deform'},
    {'name': 'Left_Index_Stretch3_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Index_04_Deform'},
    
    {'name': 'Left_Top_Middle1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_02_Deform'},
    {'name': 'Left_Top_Middle2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_03_Deform'},
    {'name': 'Left_Top_Middle2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_03_Deform'},
    {'name': 'Left_Top_Middle3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_04_Deform'},
    {'name': 'Left_Top_Middle3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_04_Deform'},
    {'name': 'Left_Middle_Stretch1_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_02_Deform'},
    {'name': 'Left_Middle_Stretch2_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_03_Deform'},
    {'name': 'Left_Middle_Stretch3_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Middle_04_Deform'},

    {'name': 'Left_Top_Ring1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_02_Deform'},
    {'name': 'Left_Top_Ring2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_03_Deform'},
    {'name': 'Left_Top_Ring2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_03_Deform'},
    {'name': 'Left_Top_Ring3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_04_Deform'},
    {'name': 'Left_Top_Ring3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_04_Deform'},
    {'name': 'Left_Ring_Stretch1_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_02_Deform'},
    {'name': 'Left_Ring_Stretch2_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_03_Deform'},
    {'name': 'Left_Ring_Stretch3_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Ring_04_Deform'},

    {'name': 'Left_Top_Pinky1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_02_Deform'},
    {'name': 'Left_Top_Pinky2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_03_Deform'},
    {'name': 'Left_Top_Pinky2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_03_Deform'},
    {'name': 'Left_Top_Pinky3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_04_Deform'},
    {'name': 'Left_Top_Pinky3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_04_Deform'},
    {'name': 'Left_Pinky_Stretch1_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_02_Deform'},
    {'name': 'Left_Pinky_Stretch2_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_03_Deform'},
    {'name': 'Left_Pinky_Stretch3_Deform',  'type': 'Deform',  'parent': 'Left_HandRig_Pinky_04_Deform'},

    {'name': 'Left_Mastoid_1_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},
    {'name': 'Left_Mastoid_2_Deform',  'type': 'Deform',  'parent': 'Left_Mastoid_1_Deform'},
    {'name': 'Left_Mastoid_3_Deform',  'type': 'Deform',  'parent': 'Left_Mastoid_2_Deform'},
    {'name': 'Left_Mastoid_4_Deform',  'type': 'Deform',  'parent': 'Left_Mastoid_3_Deform'},
    {'name': 'Left_Mastoid_5_Deform',  'type': 'Deform',  'parent': 'Left_Mastoid_4_Deform'},

    {'name': 'Left_Elbow_Fur_Main_Deform',  'type': 'Deform',  'parent': 'Left_Arm_Twist_Up_End_Deform'},
    

    {'name': 'Right_Eye_Main_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},
    {'name': 'Right_Eye_Extra_Main_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},

    {'name': 'Right_Shoulder_0_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},
    {'name': 'Right_Arm_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_0_Deform'},
    {'name': 'Right_Arm_Twist_Up_1_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_Start_Deform'},
    {'name': 'Right_Arm_Twist_Up_2_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_1_Deform'},
    {'name': 'Right_Arm_Twist_Up_3_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_2_Deform'},
    {'name': 'Right_Arm_Twist_Up_4_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_3_Deform'},
    {'name': 'Right_Arm_Twist_Up_5_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_4_Deform'},
    {'name': 'Right_Arm_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_5_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_End_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_1_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_2_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_1_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_3_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_2_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_4_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_3_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_5_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_4_Deform'},
    {'name': 'Right_Arm_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_5_Deform'},
    {'name': 'Right_Arm_Eff_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_End_Deform'},

    {'name': 'Right_HandRig_Hand_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Eff_Deform'},
    {'name': 'Right_Forearm_0_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandProp_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'}, # Added for Light
    {'name': 'Right_HandRig_Hand_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Thumb_02_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Thumb_02_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_02_Deform'},
    {'name': 'Right_HandRig_Thumb_03_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_02_Deform'},
    {'name': 'Right_HandRig_Thumb_03_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_03_Deform'},
    {'name': 'Right_HandRig_Thumb_04_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_03_Deform'},
    {'name': 'Right_HandRig_Index_01_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Index_01_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_01_Deform'},
    {'name': 'Right_HandRig_Index_02_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_01_Deform'},
    {'name': 'Right_HandRig_Index_02_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_02_Deform'},
    {'name': 'Right_HandRig_Index_03_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_02_Deform'},
    {'name': 'Right_HandRig_Index_03_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_03_Deform'},
    {'name': 'Right_HandRig_Index_04_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_03_Deform'},
    {'name': 'Right_HandRig_Middle_01_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Middle_01_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_01_Deform'},
    {'name': 'Right_HandRig_Middle_02_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_01_Deform'},
    {'name': 'Right_HandRig_Middle_02_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_02_Deform'},
    {'name': 'Right_HandRig_Middle_03_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_02_Deform'},
    {'name': 'Right_HandRig_Middle_03_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_03_Deform'},
    {'name': 'Right_HandRig_Middle_04_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_03_Deform'},
    {'name': 'Right_HandRig_Ring_01_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Ring_01_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_01_Deform'},
    {'name': 'Right_HandRig_Ring_02_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_01_Deform'},
    {'name': 'Right_HandRig_Ring_02_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_02_Deform'},
    {'name': 'Right_HandRig_Ring_03_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_02_Deform'},
    {'name': 'Right_HandRig_Ring_03_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_03_Deform'},
    {'name': 'Right_HandRig_Ring_04_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_03_Deform'},
    {'name': 'Right_HandRig_Pinky_01_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_HandRig_Pinky_01_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_01_Deform'},
    {'name': 'Right_HandRig_Pinky_02_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_01_Deform'},
    {'name': 'Right_HandRig_Pinky_02_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_02_Deform'},
    {'name': 'Right_HandRig_Pinky_03_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_02_Deform'},
    {'name': 'Right_HandRig_Pinky_03_Semi_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_03_Deform'},
    {'name': 'Right_HandRig_Pinky_04_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_03_Deform'},

    {'name': 'Right_Pelvis_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Leg_Root_Skin_Main_Deform',  'type': 'Deform',  'parent': 'Right_Pelvis_Main_Deform'},

    {'name': 'Right_Leg_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Root_Skin_Main_Deform'},
    {'name': 'Right_Leg_Twist_Up_1_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_Start_Deform'},
    {'name': 'Right_Leg_Twist_Up_2_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_1_Deform'},
    {'name': 'Right_Leg_Twist_Up_3_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_2_Deform'},
    {'name': 'Right_Leg_Twist_Up_4_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_3_Deform'},
    {'name': 'Right_Leg_Twist_Up_5_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_4_Deform'},
    {'name': 'Right_Leg_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_5_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_End_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_1_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_2_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_1_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_3_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_2_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_4_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_3_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_5_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_4_Deform'},
    {'name': 'Right_Leg_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_5_Deform'},
    {'name': 'Right_Leg_Eff_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_End_Deform'},
    {'name': 'Right_Foot_Tip_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Eff_Deform'},

    {'name': 'Right_RearLeg_Pelvis_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},

    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_1',  'type': 'Deform',  'parent': 'Right_RearLeg_Pelvis_Main_Deform'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_2',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_1'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_3',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_2'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_4_0',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_3'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_4',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_4_0'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_4_1',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_4'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_5',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_4_1'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_6',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_5'},
    {'name': 'Right_RearLeg_Rounding_Deformer_Deformer_7',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_6'},

    {'name': 'Right_RearLeg_Meta_FK_def_0_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_Rounding_Deformer_Deformer_7'},

    {'name': 'Right_RearLeg_FK_Ball_def_0_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_Meta_FK_def_0_Deform'},
    {'name': 'Right_RearLeg_FK_Toe_def_0_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_FK_Ball_def_0_Deform'},

    {'name': 'Right_Toe_LittleThumb_1_Main_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_Meta_FK_def_0_Deform'},
    {'name': 'Right_Toe_Thumb_1_Main_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_Meta_FK_def_0_Deform'},
    {'name': 'Right_Toe_Pinky_1_Main_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_FK_Toe_def_0_Deform'},
    {'name': 'Right_Toe_Middle_1_Main_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_FK_Toe_def_0_Deform'},
    {'name': 'Right_Toe_Index_1_Main_Deform',  'type': 'Deform',  'parent': 'Right_RearLeg_FK_Toe_def_0_Deform'},
    
    {'name': 'Right_Wrist_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_Wrist_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_Wrist_Int_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},
    {'name': 'Right_Wrist_Ext_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Hand_Deform'},

    {'name': 'Right_Hips_Belly_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Hips_Ft_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Hips_Side_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Hip_SideExtra_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Hips_Gluteus_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},
    {'name': 'Right_Hips_Bk_Stretch_Deform',  'type': 'Deform',  'parent': 'Spine_Start_Deform'},

    {'name': 'Right_Ham_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_End_Deform'},
    {'name': 'Right_Knee_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_End_Deform'},
    {'name': 'Right_Knee_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Knee_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_Leg_Twist_Up_End_Deform'},

    {'name': 'Right_Shoulder_Latissimus_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_0_Deform'},
    {'name': 'Right_Biceps_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_End_Deform'},
    {'name': 'Right_Elbow_Up_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_End_Deform'},
    {'name': 'Right_Elbow_Dwn_AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Elbow_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_End_Deform'},

    {'name': 'Right_ThumbBase_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_02_Deform'},
    {'name': 'Right_Top_Thumb1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_03_Deform'},
    {'name': 'Right_Top_Thumb3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_04_Deform'},
    {'name': 'Right_Top_Thumb3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_04_Deform'},
    {'name': 'Right_ThumbWeb_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_03_Deform'},
    {'name': 'Right_Thumb2_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_03_Deform'},
    {'name': 'Right_Thumb3_Stretch_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Thumb_04_Deform'},
    
    {'name': 'Right_Top_Index1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_02_Deform'},
    {'name': 'Right_Top_Index2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_03_Deform'},
    {'name': 'Right_Top_Index2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_03_Deform'},
    {'name': 'Right_Top_Index3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_04_Deform'},
    {'name': 'Right_Top_Index3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_04_Deform'},
    {'name': 'Right_Index_Stretch1_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_02_Deform'},
    {'name': 'Right_Index_Stretch2_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_03_Deform'},
    {'name': 'Right_Index_Stretch3_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Index_04_Deform'},
    
    {'name': 'Right_Top_Middle1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_02_Deform'},
    {'name': 'Right_Top_Middle2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_03_Deform'},
    {'name': 'Right_Top_Middle2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_03_Deform'},
    {'name': 'Right_Top_Middle3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_04_Deform'},
    {'name': 'Right_Top_Middle3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_04_Deform'},
    {'name': 'Right_Middle_Stretch1_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_02_Deform'},
    {'name': 'Right_Middle_Stretch2_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_03_Deform'},
    {'name': 'Right_Middle_Stretch3_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Middle_04_Deform'},

    {'name': 'Right_Top_Ring1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_02_Deform'},
    {'name': 'Right_Top_Ring2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_03_Deform'},
    {'name': 'Right_Top_Ring2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_03_Deform'},
    {'name': 'Right_Top_Ring3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_04_Deform'},
    {'name': 'Right_Top_Ring3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_04_Deform'},
    {'name': 'Right_Ring_Stretch1_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_02_Deform'},
    {'name': 'Right_Ring_Stretch2_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_03_Deform'},
    {'name': 'Right_Ring_Stretch3_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Ring_04_Deform'},

    {'name': 'Right_Top_Pinky1AngleDeformer_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_02_Deform'},
    {'name': 'Right_Top_Pinky2AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_03_Deform'},
    {'name': 'Right_Top_Pinky2AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_03_Deform'},
    {'name': 'Right_Top_Pinky3AngleDeformer1_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_04_Deform'},
    {'name': 'Right_Top_Pinky3AngleDeformer2_Main_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_04_Deform'},
    {'name': 'Right_Pinky_Stretch1_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_02_Deform'},
    {'name': 'Right_Pinky_Stretch2_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_03_Deform'},
    {'name': 'Right_Pinky_Stretch3_Deform',  'type': 'Deform',  'parent': 'Right_HandRig_Pinky_04_Deform'},

    {'name': 'Right_Mastoid_1_Deform',  'type': 'Deform',  'parent': ['Neck_Head_Deform', 'Neck_End_Deform']},
    {'name': 'Right_Mastoid_2_Deform',  'type': 'Deform',  'parent': 'Right_Mastoid_1_Deform'},
    {'name': 'Right_Mastoid_3_Deform',  'type': 'Deform',  'parent': 'Right_Mastoid_2_Deform'},
    {'name': 'Right_Mastoid_4_Deform',  'type': 'Deform',  'parent': 'Right_Mastoid_3_Deform'},
    {'name': 'Right_Mastoid_5_Deform',  'type': 'Deform',  'parent': 'Right_Mastoid_4_Deform'},

    {'name': 'Right_Elbow_Fur_Main_Deform',  'type': 'Deform',  'parent': 'Right_Arm_Twist_Up_End_Deform'},

    {'name': 'Right_Ear_1_Main_Deform',  'type': 'Deform',  'parent': 'Neck_End_Deform'},
    {'name': 'Left_Ear_1_Main_Deform',  'type': 'Deform',  'parent': 'Neck_End_Deform'},

    {'name': 'Left_Forefoot_Tip_Deform',  'type': 'Deform',  'parent': 'Left_Foreleg_Eff_Deform'},
    {'name': 'Left_Foreleg_Eff_Deform',  'type': 'Deform',  'parent': ['Left_Foreleg_Twist_Dwn_End_Deform', "Left_Foreleg_Twist_Dwn_5_Deform"]},
    {'name': 'Left_Foreleg_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Left_Foreleg_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Foreleg_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Left_Foreleg_Twist_Up_End_Deform'},
    {'name': 'Left_Foreleg_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Left_Foreleg_Twist_Up_Start_Deform'},
    {'name': 'Left_Foreleg_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_Twist_Dwn_End_Deform'},
    {'name': 'Left_Shoulder_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_Twist_Dwn_Start_Deform'},
    {'name': 'Left_Shoulder_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_Twist_Up_End_Deform'},
    {'name': 'Left_Shoulder_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Left_Shoulder_Twist_Up_Start_Deform'},
    {'name': 'Left_Shoulder_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},

    {'name': 'Right_Forefoot_Tip_Deform',  'type': 'Deform',  'parent': 'Right_Foreleg_Eff_Deform'},
    {'name': 'Right_Foreleg_Eff_Deform',  'type': 'Deform',  'parent': 'Right_Foreleg_Twist_Dwn_End_Deform'},
    {'name': 'Right_Foreleg_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Right_Foreleg_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Foreleg_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Right_Foreleg_Twist_Up_End_Deform'},
    {'name': 'Right_Foreleg_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Right_Foreleg_Twist_Up_Start_Deform'},
    {'name': 'Right_Foreleg_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_Twist_Dwn_End_Deform'},
    {'name': 'Right_Shoulder_Twist_Dwn_End_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_Twist_Dwn_Start_Deform'},
    {'name': 'Right_Shoulder_Twist_Dwn_Start_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_Twist_Up_End_Deform'},
    {'name': 'Right_Shoulder_Twist_Up_End_Deform',  'type': 'Deform',  'parent': 'Right_Shoulder_Twist_Up_Start_Deform'},
    {'name': 'Right_Shoulder_Twist_Up_Start_Deform',  'type': 'Deform',  'parent': 'Spine_End_Deform'},
]